import type { Metadata } from "next";
import "./globals.css";
import Layout from "../components/Layout";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/lib/AuthProivder";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body>
      <Toaster />
      <Layout>
        <LoginModal  />
        <RegisterModal />
        {children}
      </Layout>
      </body>
      </AuthProvider>
    </html>
  );
}
